### ISSUE TITLE
Getting the following error using python-socketio

### ISSUE THREAD

**Issue by DovaX** [miguelgrinberg/python-engineio#194] opened 2020-09-03 09:08 UTC
Hi, I got the following error with this code on the client side
```
import socketio
import asyncio

sio = socketio.AsyncClient()

async def run():    
    @sio.event()
    async def connect():
        print("I'm connected!")

    @sio.event
    async def disconnect():
        print("I'm disconnected!")

    await sio.connect('ws://127.0.0.1:5000', transports='websocket')
    await sio.sleep(2)
    print('my sid is', sio.sid)
    await sio.disconnect()

if __name__ == '__main__':
    asyncio.run(run())

```

Traceback (most recent call last):
  File "synchro.py", line 26, in <module>
    asyncio.run(run())
  File "c:\programy\python\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "c:\programy\python\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "synchro.py", line 20, in run
    await sio.connect('ws://127.0.0.1:5000', transports='websocket')
  File "C:\Users\EUROCOM\Documents\Git\DovaX\Gitlab\replicator_client-ondra_dev\venv2\lib\site-packages\socketio\asyncio_client.py", line 109, in connect
    await self.eio.connect(url, headers=headers,
  File "C:\Users\EUROCOM\Documents\Git\DovaX\Gitlab\replicator_client-ondra_dev\venv2\lib\site-packages\engineio\asyncio_client.py", line 86, in connect
    asyncio.get_event_loop().add_signal_handler(signal.SIGINT,
  File "c:\programy\python\lib\asyncio\events.py", line 536, in add_signal_handler
    raise NotImplementedError
NotImplementedError

It helped me to change version of python-engineio back to 3.13.1 where everything worked.
I used Anaconda on Windows

**Comment by miguelgrinberg** [comment] 2020-09-03 09:24
Duplicate of https://github.com/miguelgrinberg/python-socketio/issues/538. A fix will be available shortly.

**Closed by miguelgrinberg** 2020-09-03 09:24 UTC
