### ISSUE TITLE
Async client fails to connect on Windows

### ISSUE THREAD

**Issue by JoriDubrovin** [miguelgrinberg/python-engineio#196] opened 2020-09-14 06:47 UTC
In python-engineio 3.13.2, `AsyncClient.connect` calls `add_signal_handler`, which does not seem to be implemented on Windows.

To reproduce using WinPython 3.6.5:
```
> python -m venv async-win-bug
> async-win-bug\Scripts\activate
> pip install python-engineio==3.13.2 python-socketio==4.6.0 aiohttp==3.6.2
> python -c "import asyncio; import socketio; asyncio.get_event_loop().run_until_complete(socketio.AsyncClient().connect('file:///'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "...\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "...\lib\site-packages\socketio\asyncio_client.py", line 111, in connect
    engineio_path=socketio_path)
  File "...\lib\site-packages\engineio\asyncio_client.py", line 87, in connect
    async_signal_handler)
  File "...\lib\asyncio\events.py", line 499, in add_signal_handler
    raise NotImplementedError
NotImplementedError
```

Previous version works, i.e. if I replace `python-engineio==3.13.2` with `python-engineio==3.13.1`, I get a `ConnectionError` as expected.

**Comment by miguelgrinberg** [comment] 2020-10-21 22:31
Duplicate of #199.

**Closed by miguelgrinberg** 2020-10-21 22:31 UTC
