### ISSUE TITLE
Engine.IO fails to encode the data to bytes

### ISSUE THREAD

**Issue by umityayla** [miguelgrinberg/python-engineio#173] opened 2020-05-04 14:39 UTC
Hello,

I created an [issue](https://github.com/miguelgrinberg/Flask-SocketIO/issues/1238) this bug/problem over at the flask-socketio repository, but I believe this place would be more fitting. 
```
TypeError: <engineio.packet.Packet object at 0x7f65cf2c5e20> is not a byte,
[2020-04-07 14:03:07 +0000] [12] [ERROR] Error handling request,
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 114, in handle_request,
    resp.write(item),
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 328, in write,
    raise TypeError('%r is not a byte' % arg),
TypeError: <engineio.packet.Packet object at 0x7f65cecce0d0> is not a byte
```

The problem occurs when Gunicorn expects the data in "bytes" but receives them as "engineio.packet.Packet" and so raises an error. When I investigated,  the data didn't seem to be weird `{'sid': '5422ee88adf040d789525b1c4b10cf4c', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 5000}` , socket.io initiation process. Interestingly, when I tried to encode the `arg` again with `arg.encode(arg)` I didn't receive any errors. So, would it be a big mistake to do something like this;

```
(...)
if arg not byte:
    arg = arg.encode(arg)
(...)
```

**Comment by miguelgrinberg** [comment] 2020-05-04 15:09
I'm going to close this, since it is a duplicate of the other issue and you put all the info on that other one.

**Closed by miguelgrinberg** 2020-05-04 15:09 UTC
