### ISSUE TITLE
Sending binary data using client does not work

### ISSUE THREAD

**Issue by akgondber** [miguelgrinberg/python-engineio#112] opened 2019-05-27 15:41 UTC

**Comment by miguelgrinberg** [comment] 2019-05-29 15:31
Binary packets sent through WebSocket are sent as strings. I'm not sure if the problem is in the WS client itself or in how I'm using it. This issue does not exist when using the asyncio client, which uses a different websocket client.

**Comment by miguelgrinberg** [comment] 2019-05-29 16:05
@akgondber can I ask you to test the master branch of this package? I believe I have addressed the problem with binary payloads. I missed the fact that the websocket client has a separate send function for binary.

**Comment by akgondber** [comment] 2019-05-29 16:59
I have tested changes in the master branch. Now it works correctly. Thank you for the library and this fix.

**Comment by miguelgrinberg** [comment] 2019-05-29 17:41
Released as 3.7.0. Thanks!

**Closed by miguelgrinberg** 2019-05-29 17:41 UTC
Labels: bug
